M48
; DRILL file KiCad 10.0.6 date 2026-10-06T18:58:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T18:58:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X54.04Y-98.0
X54.04Y-107.0
T2
X54.0Y-54.0
X54.0Y-116.0
X146.0Y-54.0
X146.0Y-116.0
M30
